kind: Pod
apiVersion: v1
metadata:
  name: "k8s-test"
  labels:
    name: "k8s-test"
    version: "00.00"
  namespace: "default"
spec:
  containers:
  - env:
    - name: "K8STEST_PORT"
      value: "9898"
    image: "pmercado/k8stest"
    imagePullPolicy: "Always"
    name: "k8s-simple-test"
    ports:
    - containerPort: 9898
      protocol: "TCP"
  restartPolicy: "Always"
